# Generated by Django 3.0.7 on 2021-09-15 19:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legacy', '0002_auto_20210915_1524'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='local',
            unique_together={('user', 'latitude', 'longitude')},
        ),
    ]
